name: Test

on: [push]

jobs:
  test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run the setup.sh script
      timeout-minutes: 20
      run: |
        source setup.sh myemail@example.com
